apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
spec:
  isCA: true
  commonName: selfsigned-ca
  secretName: root-ca-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: internal-ca-issuer
spec:
  ca:
    secretName: root-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: search-api-certs
spec:
  secretName: search-api-certs
  dnsNames:
  - search-search-api.open-cluster-management.svc.cluster.local
  - search-search-api.open-cluster-management.svc
  - localhost
  issuerRef:
    name: internal-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: search-postgres-certs
spec:
  secretName: search-postgres-certs
  duration: 8760h0m0s
  commonName: search-postgres
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
  dnsNames:
  - search-postgres.open-cluster-management.svc.cluster.local
  - search-postgres.open-cluster-management.svc
  - localhost
  issuerRef:
    name: internal-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: search-indexer-certs
spec:
  secretName: search-indexer-certs
  dnsNames:
  - search-indexer.open-cluster-management.svc.cluster.local
  - search-indexer.open-cluster-management.svc
  - localhost
  issuerRef:
    name: internal-ca-issuer
    kind: Issuer
    group: cert-manager.io